### ISSUE TITLE
Link to official implementation, remove misleading citation

### ISSUE THREAD

**Issue by elliottower** [kyegomez/LongNet#1]
It's fine to have your own re-implementation but you need to acknowledge it as such, and link the official implementation and paper:

https://github.com/microsoft/unilm
https://arxiv.org/abs/2307.02486v1

To confirm that is indeed the correct implementation, you can look at [paperswithcode](https://paperswithcode.com/paper/longnet-scaling-transformers-to-1000000000) and see it's listed under code, and microsoft's repo lists LongNet and links to the arxiv paper.

You also include the citation on this repository, which is very misleading as this is *not* the official implementation and is not at all associated with the paper.

For people who aren't familiar with this guy, he regularly tries to steal people's work and mislead people into thinking it's his own:
https://github.com/kyegomez/tree-of-thoughts/issues/56
https://github.com/kyegomez/tree-of-thoughts/issues/74
https://github.com/kyegomez/tree-of-thoughts/issues/34 (providing the code and implementation before the authors did only means you are clout chasing and trying to mislead people)

**Comment by breadbrowser** [comment]
> Where is the code in this implementation @elliottower ?
> 
> And, where do you not see the citation?
> 
> And, how am I stealing other peoples works?
> 
> How am I misleading people?

![image](https://github.com/kyegomez/LongNet/assets/64813014/491016a1-f829-4f14-b2b4-3e3851599ea8)
this may be the reason

**Comment by elliottower** [comment]
My fault I actually was mistaken that the other repo contained the full code, it looks like it's listed there but the code isn't available yet. 

Still would be most clear to say an unofficial implementation, or to clarify that it is not affiliated with Microsoft Research. Adding a disclaimer section like https://github.com/danijar/dreamerv3#disclaimer would be best practice as well.

The reason I say it's misleading is if someone sees a repository, scrolls through it, and sees a citation, the first thing that goes through their heads is that it is the official implementation. Putting a citation section on your repository linking someone else's paper implies that you are affiliated with them. For example, note that this unofficial MuZero implementation creates a citation for its own repository but does not try to associate with the official citation.

Also, closing an issue before someone gets a chance to respond is pretty childish (but not unexpected), clearly you are trying to hide things and brush valid criticisms under the rug.

**Comment by JonathanLehner** [comment]
@elliottower I think it would be good to approach this with a constructive attitude and without hurling accusations. Regardless of whether your criticisms are justified or not, this way is unlikely to lead to a compromise. You should also be clear about what is your exact request. 
I think if there is no official code available, then it is a great contribution of @kyegomez since few people will do the effort to provide the code for other people's glory -- in the end I think for the researchers the more it shows the paper name, the better. 
So personally, I think changing the description is unnecessary. I would suggest to just copy the disclaimer from https://github.com/danijar/dreamerv3#disclaimer to the readme and be done with it.

**Comment by elliottower** [comment]
> @elliottower I think it would be good to approach this with a constructive attitude and without hurling accusations. Regardless of whether your criticisms are justified or not, this way is unlikely to lead to a compromise. You should also be clear about what is your exact request.
> I think if there is no official code available, then it is a great contribution of @kyegomez since few people will do the effort to provide the code for other people's glory -- in the end I think for the researchers the more it shows the paper name, the better.
> So personally, I think changing the description is unnecessary. I would suggest to just copy the disclaimer from https://github.com/danijar/dreamerv3#disclaimer to the readme and be done with it.

You have a point but given this guys past behavior (e.g., the fact that you can’t even reopen issues, the fact that in his other repos he’s actively tried to steal credit for things) it’s clear he doesn’t care and is just trying to take advantage of the hype train for any new paper that comes out and take credit from the authors (go read his comments in the tree of thoughts issues I linked if you don’t believe me)

**Comment by kyegomez** [comment]
> > @elliottower I think it would be good to approach this with a constructive attitude and without hurling accusations. Regardless of whether your criticisms are justified or not, this way is unlikely to lead to a compromise. You should also be clear about what is your exact request.
> 
> > I think if there is no official code available, then it is a great contribution of @kyegomez since few people will do the effort to provide the code for other people's glory -- in the end I think for the researchers the more it shows the paper name, the better.
> 
> > So personally, I think changing the description is unnecessary. I would suggest to just copy the disclaimer from https://github.com/danijar/dreamerv3#disclaimer to the readme and be done with it.
> 
> 
> 
> You have a point but given this guys past behavior (e.g., the fact that you can’t even reopen issues, the fact that in his other repos he’s actively tried to steal credit for things) it’s clear he doesn’t care and is just trying to take advantage of the hype train for any new paper that comes out and take credit from the authors (go read his comments in the tree of thoughts issues I linked if you don’t believe me)

What am I trying to steal credit from? How am I taking credit from the authors when they don't even publish their own code?

I'm implementing the papers because the authors don't release their code. I'm doing this for me not for you or anybody else.

You seem to think I'm doing this for clout but in reality I want to actually use and test this research out. Papers aren't useful, the experiments behind them are useful, and if the authors take the liberty to publish an entire paper on some extremely valuable research topic and YET do not allow for others to easily reproduce the experiment there is an grand issue at hand.

As we have strayed away from real science and have fallen into the illusion of politics and writing reports on illusions.

I keep asking you to validate your claims but you provide no definitive explanations. 

I try to stay open minded so please provide me with feedback so that I may improve.

**Comment by elliottower** [comment]
Totally fair when there’s no official code but the tree of thoughts code has exact experiment run scripts to reproduce the results. There’s nothing wrong with making an implementation, it’s just these subtle things like refusing to link the official code in the tree of thoughts repo, or putting the citation in a misleading way that makes it seem like it’s your work. Giving disclaimers that you’re not affiliated with the organizations and being generally amiable and collaborative rather than closed off and dismissive, would be a big step in the right direction. In such a small research and open source community it’s really important to work together collaboratively and respectfully. 

It would also be great if you allowed people to reopen issues, and acted less defensively with closing them instantly or repeatedly (the authors of tree of thoughts opened 3 different issues). All I want is for you to reconsider the way you interact with the community, especially as someone who’s trying to grow an organization it’s not a great way to treat people. I appreciate you saying you’re willing to accept criticism, but as they say actions speak louder than words.
